# Netlify configuration for React + Vite
[build]
  command = "npm run build"
  publish = "dist"

# Redirecionamento para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
